
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractListModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class Regels extends javax.swing.JFrame {

    /**
     * Creates new form Regels
     */
    public Regels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start2Button = new JButton();
        terugButton = new JButton();
        jLabel2 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jList1 = new JList<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        start2Button.setFont(new Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        start2Button.setForeground(new Color(255, 0, 0));
        start2Button.setText("Start");
        start2Button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                start2ButtonActionPerformed(evt);
            }
        });

        terugButton.setFont(new Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        terugButton.setForeground(new Color(255, 0, 0));
        terugButton.setText("Terug");
        terugButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                terugButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new Font("Tw Cen MT Condensed Extra Bold", 0, 70)); // NOI18N
        jLabel2.setForeground(new Color(0, 0, 153));
        jLabel2.setText("Regels");
        jLabel2.setToolTipText("");

        jList1.setFont(new Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jList1.setForeground(new Color(0, 0, 204));
        jList1.setModel(new AbstractListModel<String>() {
            String[] strings = { "- De dammen kunnen alleen op de zwarte velden worden gezet", "- Bijde spelers hebben 12 dammen", "- De dam mag schuin naar voren worden geschoven", "- Als de schijf van de tegenstander schuin van uw schijf ligt kan je deze    niet op dezelfde plek leggen", "maar als het veld er achter leeg is kan je hem daar op zetten.dit is slaan zodra de schijf is geslagen moet de schijf van het bord", "- Je wint als de tegenstander geen stenen meer op het bord heeft of al er geen zet meer gedaan kan worden" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(terugButton)
                        .addGap(18, 18, 18)
                        .addComponent(start2Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel2)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(terugButton)
                    .addComponent(start2Button))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start2ButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_start2ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Game obj = new Game();
        obj.setVisible(true);
    }//GEN-LAST:event_start2ButtonActionPerformed

    private void terugButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_terugButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu obj = new Menu();
        obj.setVisible(true);
    }//GEN-LAST:event_terugButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel2;
    private JList<String> jList1;
    private JScrollPane jScrollPane2;
    private JButton start2Button;
    private JButton terugButton;
    // End of variables declaration//GEN-END:variables
}
